language: go
jobs:
  include:
    - stage: test
      name: "Go before modules"
      go:
        - 1.10.x
      before_install:
        - go get -t -v ./...
      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - stage: test
      name: "Go with modules"
      go:
        - 1.11.x
        - 1.12.x
      install: skip
      script:
        - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
